### ISSUE TITLE
Can't open PDF on Android

### ISSUE THREAD

**Issue by Westimages** [myflashlab/PDF-ANE#3]
Hi,

I tried the demo version and followed this tutorial https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O. I got the dialog box.
I have bought a license and just replaced "pdfViewer.ane" by the new one i get.
But, the dialog box that showed up with the demo ane, doesn't show up with the new one ( in fact, nothing happen with the new one.) 
do i have to change something to set up the full version instead of demo ?

**Comment by myflashlab** [comment]
to open a pdf file you need to call the run method
```actionscript
_ex.run(File.documentsDirectory.resolvePath("sample_pdfViewer_ane.pdf"))
```
are you sure you are calling this method?

**Comment by Westimages** [comment]
Yes, this code called when i press a button :

   ```
    _ex = new PdfViewer();
			
    var src:File = File.applicationDirectory.resolvePath(lienPDF);
    var dis:File = File.documentsDirectory.resolvePath(src.name);
    if (dis.exists) dis.deleteFile();
    if (!dis.exists) src.copyTo(dis, true);
			
    _ex.run(dis);
```

And with demo version i got dialog box.

**Comment by myflashlab** [comment]
the first thing to notice is that you should not try to initialize the extension each time a button is pressed. This will lead to creating many instances of the extension unused in your project which will soon leak in your app. instead, initialize the ANE out side your button call and then whenever the button is clicked, call the ```run``` method.

*notice:* The demo dialog shows ONLY when you are initializing the extension. you are seeing it multiple times because you are initializing the extension over and over.

do this change and then tell me how it goes.

**Comment by myflashlab** [comment]
And are you sure you have added ```<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>``` to your manifest? that is a must have setting on Android.

**Comment by Westimages** [comment]
Yes i did, here is my manifest
```
<manifest android:installLocation="auto">
	<uses-sdk android:minSdkVersion="10" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-feature android:required="true" android:name="android.hardware.touchscreen.multitouch" />
	<application android:hardwareAccelerated="true" android:allowBackup="true">
		<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
	</application>
</manifest>
```
I will extract the initialize. thanks for the tip.

**Comment by Westimages** [comment]
i moved ``_ex = new PdfViewer();``to call it once. It seem that doesn't resolve my issue.

**Comment by Westimages** [comment]
In pdf ane package, it was .ane and .swc file. I added only the .ane file in library. Is that good ?

**Comment by fmorenow** [comment]
Hi, I´m having the same problem. I just bough the license, and It doesn´t work.

**Comment by Westimages** [comment]
Any idea ? or update ?

**Comment by myflashlab** [comment]
When using Flash CC you should be careful if it's not overriding your manifest .xml file because Flash CC is a bit buggy about these things unfortunately. manually open your manifest and see if your manifest is correctly including the extension? compare it to https://github.com/myflashlab/PDF-ANE/blob/master/FD/application.xml

Yet, we uploaded a [Flash CC demo project](https://github.com/myflashlab/PDF-ANE/tree/master/CC) on our github! it will work right out of the box (you just need to set the path to the .ane and .p12 file according to your own computer)

After you solved the problem after our hint above or using the demo CC project, we would appreciate if you can share with us your experience on how you solved the problem so maybe others can learn too. Thanks.

**Comment by fmorenow** [comment]
I updated the Air SDK to the latest version, and now works fine!. Thanks.

**Comment by myflashlab** [comment]
How about you @Westimages ? please update us if that is fixed for you also?

**Comment by Westimages** [comment]
Not yet. I will try to update Air SDK to the latest version too. I will let you know if it work.

**Comment by myflashlab** [comment]
We have provided you with the FlashCC sample project, so I'm not sure how I can help you more here. Maybe you want to contact us directly through http://www.myflashlabs.com/contact/ and there, our colleagues can maybe arrange an skype/teamviewer meeting for you. I'm closing this issue now as I don't think there's more help here.

**Comment by lami66** [comment]
I haved the same problem but that right now bcause I haved forgoten to add 

\<uses-sdk android:targetSdkVersion="23"/\>

inside android manifest in the application descriptor
