### ISSUE TITLE
Accessing PDFs on Apple devices

### ISSUE THREAD

**Issue by VladThought** [myflashlab/PDF-ANE#6]
We have an app that allows users to open an editable PDF file fill out data and save it. After which we take that edited PDF and upload it to the cloud. We are using you ANE to be able to open PDFs with Adobe Acrobat Reader App. It is working fine on the Android, but we are having a problem getting it to work on the Apple devices. On the Apple devices, it seems to want to copy the PDF and we don't know where it is putting the PDF file after it copies it. Is there a way to get the path of the PDF file after it gets saved?

**Comment by myflashlab** [comment]
unlike Android which allows apps have access to an identical storage, iOS apps can't simply do that. When you are trying to open a pdf file, the third-party app is not reading the file from your app directly but the iOS system copies the file and deliver it to the other app. So, no one knows where file will be copied to, you should ask the other app developers. It means this is something impossible because your PDF file is editable and you expect to have it back in your app.

Anyway, to open PDF files in iOS, there's another option which you might find very helpful... This method will not work on Android but on iOS, you can open pdf files with RichWebView ANE. read more information about that here: http://www.myflashlabs.com/how-to-open-parse-pdf-using-richwebview-ane/ and then test our RichWebView ANE for free and make sure it works the way you want or not. I guess this will be a good solution for you.
